name: Java CI with bld
on:
  push:
    branches: [ "*" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - id: cache
        uses: actions/cache@v4
        with:
          path: lib
          key: bld-${{ hashFiles('src/bld/java/**') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: ./bld clean download
      - run: ./bld compile test
